Gentran/Controllers/api/Login/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Data.SqlClient;
using System.Web;

namespace Gentran.Controllers.api
{
    public class LoginController : ApiController
    {
        private AppSettings AppSettings = new AppSettings();
        private string response = "";
        // GET api/login
        public string Get()
        {
            response = "Connected!";

            SqlConnection.ClearAllPools();
            SqlConnection connection = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DB_GEN"].ConnectionString);
            try
            {
                connection.Open();

                if (connection.State == System.Data.ConnectionState.Open)
                {
                    connection.Close();
                }

            }
            catch (Exception ex)
            {
                connection.Close();
                if (ex.Message.Contains("The server was not found or was not accessible"))
                {
                    response = "Connection failed! Trying to reconnect..";
                }
                else
                {
                    response = "Connection failed! Trying to reconnect..";
                }
            }

            return response;
        }

        // GET api/login/5
        public string Get(string id)
        {
            string[] split = id.Split(',');

            try
            {
                SqlConnection connection = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DB_GEN"].ConnectionString);
                String selectStr = "select UMId, UMUserName, UMPassword,UMStatus,UMType FROM tblUsermaster WHERE (UMUserName = @UMId OR UMEmail = @UMId OR UMId = @UMId) and UMPassword = @UMPassword";
                connection.Open();
                SqlCommand selectcmd = new SqlCommand(selectStr, connection);
                selectcmd.Parameters.Add("@UMId",split[0]);
                selectcmd.Parameters.Add("@UMPassword", AppSettings.Encrypt(split[1]));

                SqlDataReader dr;

                dr = selectcmd.ExecuteReader();
                if (dr.HasRows)
                {
                    dr.Read();

                    if (dr["UMStatus"].ToString() == "DEA")
                    {
                        connection.Close();
                        response = "Your account is deactivated!";
                    }
                    else if (dr["UMStatus"].ToString() == "DIS")
                    {
                        connection.Close();
                        response = "You are currently disabled!";
                    }

                    else
                    {
                        response = "Login Success";
                        HttpContext.Current.Session.Add("UserId", dr["UMId"].ToString());
                        HttpContext.Current.Session.Add("UserType", dr["UMType"].ToString());
                        
                        connection.Close();
                    }
                }
                else
                {
                    connection.Close();
                    response = "Invalid Login Credentials!";
                }
            }
            catch (Exception ex)
            {
                response = ex.Message;
            }
            return response;
        }

        // POST api/login
        public void Post([FromBody]string value)
        {
        }

        // PUT api/login/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/login/5
        public void Delete(int id)
        {
        }
    }
}

Gentran/Controllers/mvc/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gentran.Controllers.mvc
{
    public class AdminController : Controller
    {
        private string basePath = "";
        byte[] sessionName = new Byte[20];
        // GET: /<controller>/
        public ActionResult Index()
        {
            if (!GetSession())
            {
                basePath = HttpContext.Request.ApplicationPath.Length > 1 ? HttpContext.Request.ApplicationPath + "/" : HttpContext.Request.ApplicationPath;
                HttpContext.Response.Redirect(basePath);
            }

            ViewData["Message"] = "Sub modules";

            return View();
        }

        public bool GetSession()
        {
            if (Session.Count > 0)
                return true;

            return false;
        }
    }
}

Gentran/Controllers/mvc/RetrieveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gentran.Controllers.mvc
{
    public class RetrieveController : Controller
    {
        private string basePath = "";
        byte[] sessionName = new Byte[20];
        // GET: /<controller>/
        public ActionResult Index()
        {
            if (!GetSession())
            {
                basePath = HttpContext.Request.ApplicationPath.Length > 1 ? HttpContext.Request.ApplicationPath + "/" : HttpContext.Request.ApplicationPath;
                HttpContext.Response.Redirect(basePath);
            }

            ViewData["Message"] = "Choose retrieving process";

            return View();
        }

        public bool GetSession()
        {
            if (Session.Count > 0)
                return true;

            return false;
        }
    }
}

Gentran/Controllers/mvc/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Gentran.Controllers.mvc
{
    public class SharedController : Controller
    {
        //
        // GET: /Shared/

        public ActionResult Index()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            System.Web.HttpRuntime.UnloadAppDomain();
            return RedirectToAction("Login", "Home");
            //return View();
        }

    }
}

Gentran/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Gentran</title>

    <link rel="shortcut icon" href="~/Images/VINCE.jpg"/> 
    <link rel="stylesheet" href="~/Content/bootstrap/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    <link href="~/Content/font-awesome/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/ionicons/ionicons.min.css" rel="stylesheet" />
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="hold-transition skin-blue sidebar-mini">
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sign In", "Login", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Administrator", "Index", "Admin")</li>
                    <li>@Html.ActionLink("PO Retrieve", "Index", "Retrieve")</li>
                    <li>@Html.ActionLink("Order", "Index", "Order")</li>
                    <li>@Html.ActionLink("Monitoring", "Index", "Monitoring")</li>
                </ul>
            </div>
        </div>
    </div>*@
    @RenderSection("header_menu", required: false)
    <div class="content-wrapper">
        <section class="content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2016 - Gentran</p>
            </footer>    
        </section>
    </div>
    @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>*@
    <script src="~/Scripts/jquery/jquery-2.2.3.min.js"></script>
    <script src="~/Scripts/plugins/raphael-min.js"></script>
    <script src="~/Scripts/bootstrap-js/bootstrap.js"></script>
    <script src="~/Scripts/js/app.min.js"></script>
    <script type="text/javascript" src="~/Scripts/js/master/master_ajax.js"></script>
    <script type="text/javascript" src="~/Scripts/angular/angular.js"></script>
    <script type="text/javascript" src="~/Scripts/angular/angular-route.js"></script>
    <script type="text/javascript" src="~/Scripts/js/master/master_main.js"></script>

    <script type="text/javascript">
        window.MyApp = {};
    </script>
    <script src="~/App/App.js"></script>
    <script type="text/javascript">
        MyApp.rootPath = '@Url.Content("~")';
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>